language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - dev
install:
- mvn clean install
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
notifications:
  email: false
  webhooks:
    urls:
    - secure: "VqWdsmoY++sKZ1qRC8sPcXOY+4zPK20iwX3oMHZv8wN3qP6p24TgKbWsD/oubb7jOorFiNfcYEL6jqY87QotXcXjwdAWqT23IiQ0pB7ws79T3lGvHfvjaANMSYCZje7vTCeaHkN2JnIP/F9VS6TII2kCnnuil/tumpD0KLltfIcTCR5LA3grYVMaLBgDUHNkJ9xlgE7vUEtPbh5ZKU+b2pqLuYJGI06pWCKjYe8JOI259QD0Z56qkFwuP5RLVIAZ5vFFFjcM4zjvXp7y3gIV8p9qgKT96BOrEQ3faD/nL8lmKKhZ+UyrlEa66P0kE6J9wCIuSMwtVqtGgrzTcH4fjUYnU8vX0nm8S2zJ1cJWthdXcZ3U9XYz7dStreFVjtXacKu4rNHv5biVoFFflUI6s15gPU3vDfoGBeS5xAuD2KOu+R+MVsQqov2qtiZ4Kpi6hQgK4B4U999C2b/gPvA7f8IjTM+dBYk3EKEoslnDdTVnPP6VjJyDhHbzCIa4xyn1yBvEJ8WINeEW6fXY/pySrIq4fgVqQz28irij7Bcgo3Cir5Geps3h9LPIqqqFM//uiHbHyGvIt3WeNjdBcaQReW9orNtDUmon5B4wEybPx5GueLOIu51QqHuZzE6RuXNqoJpTilTxjSTozc6Hvb1y7D3vIXpz30duRRy55Wp3un0="
    - secure: "glYQI0iVp6pLU/rP5/Ckod/cOLTdiAPXoqa+5vCr1D84ewbnmFWX7ylSL7SHuK35f4IrfTYCoTHXpTgF0lstUg6+2iR1VsdbxacR+cFac9kkyU1DCKKjspZw30z6weRo8zTCNDkPRJlfXWNO9ZQDlJZjLxvK40ObMAB4uW6dCx4gs19KzbEJIWXpRGiyUzxlBgNJ6LI1Wr4kp3y4m4IKTK/xe6lI3RgeJtI6ctdIbuI5hgOqrFCMF+is/S/7B/ns/AgYE/TtpRZdQzmxKKDArhdAdT3j66xmGDhDKfvDWs9VsWwoUZwKfoKAXe2KsZqvzSiv17IYESVDDqpghXbv3s0PdgnELc2DYYUSrckGoTES2l6yO4ald0dJfBFGL91JtyfygnPyhWqPx1pPgD0VIzrn6uNX6Bkh2EM5ip2Z0OWhQ7CXLcdQlxU3wyvmEDWN7EQSDiCPODMah/BU5ZZmgdEizOPFuLu+noV52JkLVYEOqQor8sTWPi/rgdobBvowlz8wgoB7uypF8b9SmYNIARrNWdGl4rE62/a3E/Kx1m1XA8SzT+LCDP0a06PuoIQcpq7IkWpsRfZqJQSuUitCcyd+2Lgc3NgkH1rU2mOMlN3KaU856da6iOImzBYsagU+MsdBpbiRUsx0ZVCn5nZc0YSvOdz595L06TAF1Tkd55s="